### ISSUE TITLE
Intellisense is not working when i created component with createRemoteVueComponent

### ISSUE THREAD

**Issue by hamza-rd** [Shopify/remote-dom#239]
i am using @remote-ui/vue package
const RemoteButton = createRemoteVueComponent<'Button', {onPress(): void}>( 'Button', ); //intellisense for onPress does not work const RemoteButton = createRemoteReactComponent<'Button', {onPress(): void}>( 'Button', );// intellisense for onPress works

intellisense in vue js is not working but in react works i am expecting it should work as it is working with react and i am also using jsx in vue but why it is not working.

**Comment by lemonmade** [comment]
Hi @hamza-rd. I've left a more detailed comment on the discussion topic you opened about [some major changes to this project that affect how you can pair it with Vue](https://github.com/Shopify/remote-dom/discussions/241#discussioncomment-8522344).
