### ISSUE TITLE
Support for Suspense

### ISSUE THREAD

**Issue by timvandam** [Shopify/remote-dom#438]
Is support for Suspense something that is planned? Currently trying to use Suspense in a POS UI Extension but getting an error:

```ts
unhideInstance is not a function.
(In 'unhideInstance(node.stateNode, node.memoizedProps)', 'unhideInstance' is undefined)
```

Perhaps posting in the wrong repo since it seems like POS UI extensions still use the remote-ui rather than remote-dom. I suppose that remote-dom works fine since it does not provide its own reconciler?

**Comment by lemonmade** [comment]
Hey Tim. You're in the mostly correct place, but you're a bit ahead of Shopify here — we do still use [`@remote-ui` libraries, which are on the `remote-ui` branch of this repo](https://github.com/Shopify/remote-dom/tree/remote-ui), not Remote DOM. We are working to transition to Remote DOM for UI extensions, which should allow us to use the built-in support for Suspense provided by `react-dom`.
